-- Database Schema for Scrapper Bot
-- Run this in the Supabase SQL Editor

-- 1. Bot Stats Table
-- Tracks global statistics for the bot
CREATE TABLE IF NOT EXISTS bot_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_started_at TIMESTAMPTZ,
    total_posts_all_time INTEGER DEFAULT 0
);

-- 2. Daily Stats Table
-- Tracks posts per day for visual graphs
CREATE TABLE IF NOT EXISTS daily_stats (
    date DATE PRIMARY KEY,
    posts_count INTEGER DEFAULT 0
);

-- 3. Runs History Table
-- Logs every execution cycle of the bot
CREATE TABLE IF NOT EXISTS runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    slot INTEGER NOT NULL,
    scheduled_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    status TEXT,
    posts_sent INTEGER DEFAULT 0,
    source_counts JSONB,
    error TEXT,
    UNIQUE(date, slot)
);

-- 4. Posted News Tracking Table
-- Prevents duplicate posts by storing normalized titles
CREATE TABLE IF NOT EXISTS posted_news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    normalized_title TEXT NOT NULL,
    full_title TEXT,
    posted_date DATE,
    posted_at TIMESTAMPTZ DEFAULT NOW(),
    source TEXT,
    category TEXT,
    run_id BIGINT REFERENCES runs(id),
    slot INTEGER
);

-- Index for faster lookups on deduplication
CREATE INDEX IF NOT EXISTS idx_posted_news_lookup ON posted_news (normalized_title, posted_date);


-- 5. RPC Functions (Remote Procedure Calls) needed by the bot

-- Function: increment_daily_stats
-- Increments the post count for a specific date, or inserts a new row if it doesn't exist.
-- Used to safely update stats atomically.
CREATE OR REPLACE FUNCTION increment_daily_stats(row_date DATE)
RETURNS VOID AS $$
BEGIN
    INSERT INTO daily_stats (date, posts_count)
    VALUES (row_date, 1)
    ON CONFLICT (date)
    DO UPDATE SET posts_count = daily_stats.posts_count + 1;
END;
$$ LANGUAGE plpgsql;

-- Function: increment_bot_stats
-- Increments the total all-time post count.
-- Assumes the python code ensures at least one row exists in bot_stats.
CREATE OR REPLACE FUNCTION increment_bot_stats()
RETURNS VOID AS $$
BEGIN
    UPDATE bot_stats
    SET total_posts_all_time = total_posts_all_time + 1;
END;
$$ LANGUAGE plpgsql;
