-- ========================================
-- FIXED SUPABASE SCHEMA FOR NEWS BOT
-- ========================================
-- Includes all fixes for:
-- - Strong spam detection
-- - Proper status tracking
-- - Efficient deduplication
-- - Performance optimizations
-- - MERGED DC + ANIME NEWS INTO ONE CHANNEL
-- ========================================

-- 1. Bot Stats Table (Global Statistics)
CREATE TABLE IF NOT EXISTS bot_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_started_at TIMESTAMPTZ DEFAULT NOW(),
    total_posts_all_time INTEGER DEFAULT 0,
    last_run_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Daily Stats Table (Daily Tracking) - UPDATED FOR MERGED CHANNELS
CREATE TABLE IF NOT EXISTS daily_stats (
    date DATE PRIMARY KEY,
    posts_count INTEGER DEFAULT 0,
    anime_posts INTEGER DEFAULT 0,  -- Now includes DC news
    world_posts INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Runs History Table (Execution Logs)
CREATE TABLE IF NOT EXISTS runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    slot INTEGER NOT NULL,
    scheduled_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    status TEXT CHECK (status IN ('started', 'success', 'failed', 'skipped')),
    posts_sent INTEGER DEFAULT 0,
    source_counts JSONB,
    error TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(date, slot)
);

-- 4. Posted News Tracking Table (CRITICAL FOR DEDUPLICATION)
CREATE TABLE IF NOT EXISTS posted_news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Deduplication fields
    normalized_title TEXT NOT NULL,  -- For fuzzy matching
    full_title TEXT NOT NULL,
    article_url TEXT,
    
    -- Date tracking (IST)
    posted_date DATE NOT NULL,  -- Date in IST
    posted_at TIMESTAMPTZ DEFAULT NOW(),  -- Exact timestamp
    
    -- Source tracking
    source TEXT NOT NULL,
    category TEXT,
    
    -- Channel tracking - UPDATED FOR MERGED CHANNELS
    channel_id TEXT,  -- Which channel it was posted to
    channel_type TEXT CHECK (channel_type IN ('anime', 'world')),  -- Removed 'dc' - now merged with 'anime'
    
    -- Status tracking (CRITICAL FOR SPAM PREVENTION)
    status TEXT DEFAULT 'sent' CHECK (status IN ('attempted', 'sent', 'failed')),
    
    -- Metadata
    run_id BIGINT REFERENCES runs(id) ON DELETE SET NULL,
    slot INTEGER,
    retry_count INTEGER DEFAULT 0,
    
    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Indexes for Performance (CRITICAL)
CREATE INDEX IF NOT EXISTS idx_posted_news_lookup 
    ON posted_news (normalized_title, posted_date);

CREATE INDEX IF NOT EXISTS idx_posted_news_date 
    ON posted_news (posted_date DESC);

CREATE INDEX IF NOT EXISTS idx_posted_news_source 
    ON posted_news (source, posted_date);

CREATE INDEX IF NOT EXISTS idx_posted_news_status 
    ON posted_news (status, posted_date);

CREATE INDEX IF NOT EXISTS idx_runs_date_slot 
    ON runs (date, slot);

-- 6. Atomic Increment Functions (CRITICAL FOR CONCURRENCY)

-- Increment daily stats atomically - UPDATED FOR MERGED CHANNELS
CREATE OR REPLACE FUNCTION increment_daily_stats(row_date DATE)
RETURNS VOID AS $$
BEGIN
    INSERT INTO daily_stats (date, posts_count)
    VALUES (row_date, 1)
    ON CONFLICT (date)
    DO UPDATE SET 
        posts_count = daily_stats.posts_count + 1,
        updated_at = NOW();
END;
$$ LANGUAGE plpgsql;

-- Increment bot stats atomically
CREATE OR REPLACE FUNCTION increment_bot_stats()
RETURNS VOID AS $$
BEGIN
    -- Ensure at least one row exists
    INSERT INTO bot_stats (total_posts_all_time, last_run_at)
    VALUES (1, NOW())
    ON CONFLICT (id) DO UPDATE SET 
        total_posts_all_time = bot_stats.total_posts_all_time + 1,
        last_run_at = NOW(),
        updated_at = NOW();
    
    -- If no row existed, the insert above created it
    -- If row existed, it was updated
END;
$$ LANGUAGE plpgsql;

-- 7. Helper Functions - UPDATED FOR MERGED CHANNELS

-- Get daily summary - UPDATED
CREATE OR REPLACE FUNCTION get_daily_summary(target_date DATE)
RETURNS TABLE(
    total_posts BIGINT,
    anime_posts BIGINT,  -- Now includes DC news
    world_posts BIGINT,
    sources JSON
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        COUNT(*)::BIGINT as total_posts,
        COUNT(*) FILTER (WHERE channel_type = 'anime')::BIGINT as anime_posts,  -- Includes DC
        COUNT(*) FILTER (WHERE channel_type = 'world')::BIGINT as world_posts,
        json_agg(json_build_object('source', source, 'count', cnt)) as sources
    FROM (
        SELECT source, COUNT(*) as cnt
        FROM posted_news
        WHERE posted_date = target_date AND status = 'sent'
        GROUP BY source
    ) source_counts;
END;
$$ LANGUAGE plpgsql;

-- Check for duplicate (fuzzy matching helper)
CREATE OR REPLACE FUNCTION check_duplicate(
    title_to_check TEXT,
    days_back INTEGER DEFAULT 7
)
RETURNS TABLE(
    is_duplicate BOOLEAN,
    matched_title TEXT,
    similarity FLOAT
) AS $$
DECLARE
    normalized TEXT;
    min_date DATE;
BEGIN
    -- Normalize the input title
    normalized := LOWER(REGEXP_REPLACE(title_to_check, '[^\w\s]', '', 'g'));
    min_date := CURRENT_DATE - days_back;
    
    RETURN QUERY
    SELECT 
        TRUE as is_duplicate,
        full_title as matched_title,
        SIMILARITY(normalized_title, normalized) as similarity
    FROM posted_news
    WHERE posted_date >= min_date
        AND SIMILARITY(normalized_title, normalized) > 0.85
    ORDER BY similarity DESC
    LIMIT 1;
    
    -- If no match found, return false
    IF NOT FOUND THEN
        RETURN QUERY SELECT FALSE, NULL::TEXT, 0::FLOAT;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- 8. Cleanup Old Data (Optional - Run Manually)
CREATE OR REPLACE FUNCTION cleanup_old_posts(days_to_keep INTEGER DEFAULT 30)
RETURNS INTEGER AS $$
DECLARE
    deleted_count INTEGER;
BEGIN
    DELETE FROM posted_news
    WHERE posted_date < CURRENT_DATE - days_to_keep
        AND status = 'sent';
    
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

-- 9. Row Level Security (RLS)
ALTER TABLE posted_news ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE bot_stats ENABLE ROW LEVEL SECURITY;

-- Policies for service role (bot) - Full access
CREATE POLICY "Service role full access on posted_news"
    ON posted_news FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Service role full access on daily_stats"
    ON daily_stats FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Service role full access on runs"
    ON runs FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Service role full access on bot_stats"
    ON bot_stats FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Policies for authenticated users - Read only
CREATE POLICY "Users can view posted_news"
    ON posted_news FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Users can view daily_stats"
    ON daily_stats FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Users can view runs"
    ON runs FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Users can view bot_stats"
    ON bot_stats FOR SELECT
    TO authenticated
    USING (true);

-- 10. Triggers for auto-updating timestamps
CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_posted_news_timestamp
    BEFORE UPDATE ON posted_news
    FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

CREATE TRIGGER set_daily_stats_timestamp
    BEFORE UPDATE ON daily_stats
    FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

CREATE TRIGGER set_bot_stats_timestamp
    BEFORE UPDATE ON bot_stats
    FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

-- 11. Views for Analytics - UPDATED FOR MERGED CHANNELS

-- Recent activity view
CREATE OR REPLACE VIEW recent_activity AS
SELECT 
    pn.posted_date,
    pn.source,
    pn.channel_type,
    pn.status,
    pn.full_title,
    pn.posted_at
FROM posted_news pn
WHERE pn.posted_date >= CURRENT_DATE - INTERVAL '7 days'
ORDER BY pn.posted_at DESC;

-- Daily summary view - UPDATED
CREATE OR REPLACE VIEW daily_summary AS
SELECT 
    ds.date,
    ds.posts_count as total_posts,
    COALESCE(anime.cnt, 0) as anime_posts,  -- Now includes DC news
    COALESCE(world.cnt, 0) as world_posts
FROM daily_stats ds
LEFT JOIN (
    SELECT posted_date, COUNT(*) as cnt 
    FROM posted_news 
    WHERE channel_type = 'anime' AND status = 'sent'  -- Includes DC news
    GROUP BY posted_date
) anime ON ds.date = anime.posted_date
LEFT JOIN (
    SELECT posted_date, COUNT(*) as cnt 
    FROM posted_news 
    WHERE channel_type = 'world' AND status = 'sent'
    GROUP BY posted_date
) world ON ds.date = world.posted_date
WHERE ds.date >= CURRENT_DATE - INTERVAL '30 days'
ORDER BY ds.date DESC;

-- Source health view
CREATE OR REPLACE VIEW source_health AS
SELECT 
    source,
    COUNT(*) as total_posts,
    COUNT(*) FILTER (WHERE status = 'sent') as successful_posts,
    COUNT(*) FILTER (WHERE status = 'failed') as failed_posts,
    COUNT(*) FILTER (WHERE status = 'attempted') as attempted_posts,
    MAX(posted_at) as last_post_time,
    ROUND(
        COUNT(*) FILTER (WHERE status = 'sent')::NUMERIC / 
        NULLIF(COUNT(*)::NUMERIC, 0) * 100, 
        2
    ) as success_rate
FROM posted_news
WHERE posted_date >= CURRENT_DATE - INTERVAL '7 days'
GROUP BY source
ORDER BY total_posts DESC;

-- 12. Initialize Default Data
INSERT INTO bot_stats (bot_started_at, total_posts_all_time)
VALUES (NOW(), 0)
ON CONFLICT (id) DO NOTHING;

-- 13. Performance Hints
-- Add comments for database documentation
COMMENT ON TABLE posted_news IS 'Tracks all posted news with strong deduplication';
COMMENT ON COLUMN posted_news.normalized_title IS 'Normalized title for fuzzy matching (lowercase, no punctuation)';
COMMENT ON COLUMN posted_news.status IS 'Post status: attempted (before send), sent (success), failed (error)';
COMMENT ON COLUMN posted_news.channel_type IS 'Channel type: anime (includes DC news), world';
COMMENT ON TABLE daily_stats IS 'Daily aggregated statistics';
COMMENT ON TABLE runs IS 'Execution history of bot runs';
COMMENT ON FUNCTION increment_daily_stats IS 'Atomically increment daily post count';
COMMENT ON FUNCTION increment_bot_stats IS 'Atomically increment all-time post count';

-- ========================================
-- MIGRATION COMPLETE - MERGED CHANNELS
-- ========================================
-- Features Implemented:
-- ✅ Strong spam detection with normalized titles
-- ✅ Status tracking (attempted/sent/failed)
-- ✅ Efficient indexes for fast lookups
-- ✅ Atomic increment functions
-- ✅ MERGED DC + ANIME into single channel type
-- ✅ 7-day deduplication window
-- ✅ Performance optimizations
-- ✅ RLS policies for security
-- ✅ Helper functions and views
-- ✅ Auto-cleanup capability
-- ========================================

-- To enable fuzzy matching extension (if not already enabled):
-- CREATE EXTENSION IF NOT EXISTS pg_trgm;